---
# 测试单个代理的网站连通性

- name: 初始化代理测试结果
  set_fact:
    proxy_name: "{{ proxy_item.inventory_hostname }}"
    proxy_tests: []
    successful_count: 0
    failed_count: 0

- name: 测试代理对各网站的连通性
  shell: |
    {% if proxy_item.proxy_username != '' and proxy_item.proxy_password != '' %}
    # 使用带认证的代理
    curl -x "{{ proxy_item.proxy_url | regex_replace('^http://', 'http://' + proxy_item.proxy_username + ':' + proxy_item.proxy_password + '@') }}" \
         -I -s \
         --connect-timeout {{ connection_timeout }} \
         --max-time {{ website_item.request_timeout | default(default_timeout) }} \
         -A "{{ http_config.user_agent }}" \
         {% if not http_config.validate_certs %}--insecure{% endif %} \
         -w "CURL_STATUS_CODE:%{http_code};CURL_TIME_TOTAL:%{time_total}\n" \
         -o /dev/null \
         "{{ website_item.test_url }}"
    {% else %}
    # 使用无认证的代理
    curl -x "{{ proxy_item.proxy_url }}" \
         -I -s \
         --connect-timeout {{ connection_timeout }} \
         --max-time {{ website_item.request_timeout | default(default_timeout) }} \
         -A "{{ http_config.user_agent }}" \
         {% if not http_config.validate_certs %}--insecure{% endif %} \
         -w "CURL_STATUS_CODE:%{http_code};CURL_TIME_TOTAL:%{time_total}\n" \
         -o /dev/null \
         "{{ website_item.test_url }}"
    {% endif %}
  register: website_test_result
  failed_when: false
  loop: "{{ test_websites }}"
  loop_control:
    loop_var: website_item
    label: "{{ website_item.inventory_hostname }}"

- name: 处理每个网站的测试结果
  set_fact:
    proxy_tests: "{{ proxy_tests + [test_result] }}"
    successful_count: "{{ successful_count | int + (1 if test_result.status == 'SUCCESS' else 0) }}"
    failed_count: "{{ failed_count | int + (1 if test_result.status == 'FAILED' else 0) }}"
  vars:
    curl_output: "{{ website_test_result.results[item_index].stdout if website_test_result.results is defined and website_test_result.results[item_index].stdout is defined else '' }}"
    curl_status_match: "{{ curl_output | regex_search('CURL_STATUS_CODE:(\\d+)', '\\1') }}"
    curl_time_match: "{{ curl_output | regex_search('CURL_TIME_TOTAL:([0-9.]+)', '\\1') }}"
    curl_status_code: "{{ curl_status_match[0] if curl_status_match else '000' }}"
    curl_time_total: "{{ curl_time_match[0] if curl_time_match else '0' }}"
    curl_return_code: "{{ website_test_result.results[item_index].rc if website_test_result.results is defined and website_test_result.results[item_index].rc is defined else 1 }}"
    curl_stderr: "{{ website_test_result.results[item_index].stderr if website_test_result.results is defined and website_test_result.results[item_index].stderr is defined else '' }}"
    test_result:
      website: "{{ website_test_result.results[item_index].website_item.inventory_hostname if website_test_result.results is defined else test_websites[item_index].inventory_hostname }}"
      url: "{{ website_test_result.results[item_index].website_item.test_url if website_test_result.results is defined else test_websites[item_index].test_url }}"
      status: "{{ 'SUCCESS' if website_test_result.results is defined and curl_return_code == 0 and curl_status_code | int in status_codes.success else 'FAILED' }}"
      status_code: "{{ curl_status_code | int if curl_status_code != '000' else -1 }}"
      response_time: "{{ (curl_time_total | float * 1000) | round(2) if curl_time_total != '0' else -1 }}"
      error_msg: "{{ curl_stderr if curl_return_code != 0 else ('HTTP状态: ' + curl_status_code if curl_status_code | int not in status_codes.success else '') }}"
      timestamp: "{{ current_timestamp }}"
  loop: "{{ range(0, test_websites | length) | list }}"
  loop_control:
    loop_var: item_index

- name: 处理检查模式的测试结果
  set_fact:
    proxy_tests: "{{ proxy_tests + [test_result] }}"
    failed_count: "{{ failed_count | int + 1 }}"
  vars:
    test_result:
      website: "{{ test_websites[item_index].inventory_hostname }}"
      url: "{{ test_websites[item_index].test_url }}"
      status: "SKIPPED"
      status_code: -1
      response_time: -1
      error_msg: "检查模式 - 测试未执行"
      timestamp: "{{ current_timestamp }}"
  loop: "{{ range(0, test_websites | length) | list }}"
  loop_control:
    loop_var: item_index
  when: ansible_check_mode and website_test_result.results is not defined

- name: 计算代理成功率
  set_fact:
    proxy_success_rate: "{{ (successful_count | int * 100 / (successful_count | int + failed_count | int)) | round(2) if (successful_count | int + failed_count | int) > 0 else 0 }}"

- name: 判断代理整体状态
  set_fact:
    proxy_status: "{{ 'HEALTHY' if proxy_success_rate | float >= monitoring.thresholds.min_success_rate | float else 'UNHEALTHY' }}"

- name: 存储代理测试结果
  set_fact:
    proxy_test_results: "{{ proxy_test_results | combine({proxy_name: {
      'proxy_name': proxy_name,
      'proxy_url': proxy_item.proxy_url,
      'status': proxy_status,
      'success_rate': proxy_success_rate,
      'successful_tests': successful_count,
      'failed_tests': failed_count,
      'total_tests': (successful_count | int + failed_count | int),
      'test_details': proxy_tests,
      'timestamp': current_timestamp
    }}) }}"