---
# Default configuration for the monitor_proxies role
monitor_config:
  proxies:
    - name: "example_proxy"
      http: "http://proxy.example.com:8080"
      https: "https://proxy.example.com:8080"
      enabled: true
  sites:
    - name: "Google"
      url: "https://www.google.com"
      validate_certs: true
    - name: "Example"
      url: "http://www.example.com"

# Global monitoring settings
monitor_settings:
  retries: 3
  timeout_seconds: 30
  max_latency_ms: 5000
  allowed_status_codes: [200, 201, 202, 301, 302]
  parallel_limit: 10

# Output settings
output_settings:
  html_report_path: "/tmp/monitoring_report.html"
  json_log_path: "/tmp/monitoring_results.json"
  send_email: false
  email_settings:
    smtp_server: "localhost"
    smtp_port: 25
    from_email: "monitoring@example.com"
    to_emails: ["admin@example.com"]
    subject: "Proxy Monitoring Report"