---
# 代理监控系统主playbook
- name: 代理状态和网站连通性监控
  hosts: localhost
  gather_facts: true
  vars_files:
    - ../group_vars/all.yml
  vars:
    start_time: "{{ ansible_date_time.iso8601 }}"
    
  tasks:
    - name: 创建日志目录
      file:
        path: "{{ monitoring.logging.log_dir }}"
        state: directory
        mode: '0755'

    - name: 初始化监控结果变量
      set_fact:
        monitoring_results: []

    - name: 执行代理监控任务
      include_role:
        name: proxy-monitor

    - name: 发送告警邮件
      include_role:
        name: proxy-monitor
        tasks_from: send_alerts
      when: 
        - email_config.enabled | default(false)
        - proxy_test_results is defined

    - name: 监控状态总结
      debug:
        msg: "代理监控周期已完成。详细日志请查看: {{ monitoring.logging.log_dir }}/{{ monitoring.logging.log_file }}"